### PR TITLE
CSS -> SCSS with BS4 variables, fixed font path

### PR DESCRIPTION
**Pull request by LORDofDOOM**
Same as https://github.com/ArgoZhang/BootstrapBlazor/pull/32 but with fixed fonts, and not included BS4 in bootstrap.blazor.css, also the sourcemaps are dropped for *.min versions

### CODE REVIEW

**Comment by ArgoZhang** [comment]
nice！thank you

**Comment by ArgoZhang** [comment]
@LORDofDOOM hi sorry for disturb you again, i had found someting after merge #35 

- fa-font correct
- SweetAlert component has a little promble. missing css animation

### NPM Issue
setup `npm` enviroment is very difficult cause by I'm in China. run npm very very slow.

### css solution in `BB` (BootstrapBlazor)

1. install `Bundler & Minifier` visx
2. edit the `bundleconfig.json`
3 pack the css & js under `lib` folder into `bootstrap.blazor.min.css` and `bootstrap.blazor.min.js` not include `*.map` file

Do you have any suggestions for run `npm`?

**Comment by pomeara** [comment]
@ArgoZhang  have you tried a mirror of npn within china 

https://developer.aliyun.com/mirror/NPM?from=tnpm

**Comment by ArgoZhang** [comment]
@pomeara 
It's a little difficult to build NPM environment in China, but it can be built. However, many people don't like `NPM`, especially. Net developers. If `BB` integrates `NPM` into the project, it will raise the threshold of entry. Therefore, I don't want to integrate additional environment into `BB` project, so I wanna keep `BB` development environment simple

**Comment by LORDofDOOM** [comment]
@ArgoZhang I've just merged in the latest CSS changes into the fork. If you find any option to get nodejs/NPM running let me know.

**Comment by ArgoZhang** [comment]
@LORDofDOOM sure! thank you.

**Pull request merged**
