### PR TITLE
CSS -> SCSS with BS4 variables

### PR DESCRIPTION
**Pull request by LORDofDOOM**
Hi,

I've recreated the CSS to SCSS with the BS4 color variables and the option to change the base colors into _variables.scss.

The bootstrap.blazor.bundle.css, bootstrap.blazor.css and the min files are getting created from the node script.

To test just:

npm install
npm run css

or (to development and recreation in realtime) use:
npm run watch-css

Please let me know if there are any changes needed :-)

Thank you for your great project

### CODE REVIEW

**Comment by ArgoZhang** [comment]
Hey @LORDofDOOM, thank you for contribution

**Comment by ArgoZhang** [comment]
hi @LORDofDOOM 

I'm very sorry to disturb you, I had some problems after merging PR.

- missing fa-font resource
- css file size from 315K to 1.5M

so i'm very sorry revert this PR for now. cloud you check it again and resubmit PR?

**Comment by LORDofDOOM** [comment]
@ArgoZhang 

No problem  - I'm a little bit confused about the size - In my case it's 295KB for the complete bundle (bootstrap.blazor.bundle.min.css) and 226KB with Bootstrap only (bootstrap.blazor.min.css). Or did you include the debug .map files in this calculation ? I could create the min version without source maps if you want

I'll create a new PR without included Bootstrap (only variables, should be the same size as before)

The fa-font is wrong, sry about that, I'll add the correct path to the variable :-)

**Comment by ArgoZhang** [comment]
@LORDofDOOM thanks for you reply. sure. not mind the file size issue. maybe it's my fault. please fix the fa-font missing issue. thank you very much.

**Comment by LORDofDOOM** [comment]
@ArgoZhang I've created a new PR with fixed fonts, no BS4 for non bundle version and dropped sourcemaps for *.min (productive) versions :-)

https://github.com/ArgoZhang/BootstrapBlazor/pull/35

**Pull request merged**
